export const PRODUCT_NAME = "KEY CRAFT 10000";

export const PHRASES_PER_MISSION = 20;
export const MISSIONS_PER_DISTRICT = 10;
export const DISTRICTS_PER_ZONE = 5;
export const MISSIONS_PER_ZONE = MISSIONS_PER_DISTRICT * DISTRICTS_PER_ZONE;

export const TOTAL_ZONES = 10;
export const TOTAL_DISTRICTS = TOTAL_ZONES * DISTRICTS_PER_ZONE;
export const TOTAL_MISSIONS = TOTAL_ZONES * MISSIONS_PER_ZONE;
export const TOTAL_PHRASES = TOTAL_MISSIONS * PHRASES_PER_MISSION;

export const WORLD_ONE_MISSIONS = 250;
export const WORLD_ONE_PHRASES = WORLD_ONE_MISSIONS * PHRASES_PER_MISSION;
